name: Build & Publish raft-tech/datahub

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/datahub-frontend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            raft-tech/datahub:latest
            raft-tech/datahub:1.0.0
            ghcr.io/raft-tech/datahub:latest
            ghcr.io/raft-tech/datahub:1.0.0
