name: Build and Push Docker container

on: 
  push:
    branches:
      - master

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: docker build -t raft-tech/datahub-frontend:latest -f ./docker/datahub-frontend/Dockerfile .

    - name: Setup GitHub Container Registry
      run: echo "${{secrets.CR_PAT}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: push to GitHub Container Registry
      run:  docker push ghcr.io/raft-tech/datahub-frontend:latest