name: datahub-frontend-react docker
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  push_to_registries:
    name: Build and Push Docker Image to Github Registry
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push image
        uses: docker/build-push-action@v2

        with:
          file: ./docker/datahub-frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            raft-tech/datahub:latest
            ghcr.io/raft-tech/datahub:latest
          push: true
