name: publish

on: [push]

jobs:
  publish-df-datahub-frontend-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the df-datahub-frontend Docker image
      run: |
        docker build . --tag ghcr.io/raft-tech/datahub:latest
        docker run ghcr.io/raft-tech/datahub:latest
        docker push ghcr.io/raft-tech/datahub:latest